backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
media_library:
  name: github
  branch: main

collections:
  - name: Books
    label: Books
    folder: "books"
    create: true
    slug: "{{slug}}"
    format: json
    fields:
      - label: Título
        name: titulo
        widget: string
        required: true
      - label: Autor
        name: autor
        widget: string
        required: true
      - label: Gênero
        name: genero
        widget: string
        required: true
      - label: Capa
        name: capa
        widget: image
        required: true
      - label: Por Que Ler?
        name: porqueLer
        widget: text
        required: true
      - label: Para Quem?
        name: paraQuem
        widget: text
        required: true
      - label: Destaque
        name: destaque
        widget: boolean
        required: false
      - label: Link
        name: link
        widget: string
        required: true