backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/livros" # Onde as capas serão salvas
public_folder: "/assets/images/livros"

collections:
  - name: "livros"
    label: "Livros"
    folder: "_livros" # Pasta onde os arquivos dos livros serão criados
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Data da Leitura", name: "date", widget: "datetime" }
      - { label: "Capa do Livro", name: "image", widget: "image" }
      - { label: "Resenha/Comentário", name: "body", widget: "markdown" }
      - { label: "Categoria", name: "category", widget: "select", options: ["Ficção", "Não-Ficção", "Técnico", "IA", "Outros"] }
