backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/livros"
public_folder: "/assets/images/livros"

collections:
  - name: "livros"
    label: "Livros"
    folder: "_livros"
    create: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Corpo", name: "body", widget: "markdown" }
